#!/bin/sh

mono cbrexporter.exe indicators Table1.2 > ../raw/indicators/Table1.2.xml
mono cbrexporter.exe indicators Table1.9 > ../raw/indicators/Table1.9.xml
mono cbrexporter.exe indicators Table1.16 > ../raw/indicators/Table1.16.xml
mono cbrexporter.exe indicators Table1.6 > ../raw/indicators/Table1.6.xml
mono cbrexporter.exe indicators Tab26.1 > ../raw/indicators/Tab26.1.xml
mono cbrexporter.exe indicators Table21.1 > ../raw/indicators/Table21.1.xml
mono cbrexporter.exe indicators Table21.2 > ../raw/indicators/Table21.2.xml
mono cbrexporter.exe indicators Table1.4 > ../raw/indicators/Table1.4.xml
mono cbrexporter.exe indicators Table1.5 > ../raw/indicators/Table1.5.xml
mono cbrexporter.exe indicators Table1.14 > ../raw/indicators/Table1.14.xml
mono cbrexporter.exe indicators Table1.11 > ../raw/indicators/Table1.11.xml
mono cbrexporter.exe indicators Tab30.2 > ../raw/indicators/Tab30.2.xml
mono cbrexporter.exe indicators Table25.2 > ../raw/indicators/Table25.2.xml
mono cbrexporter.exe indicators Tab30.1 > ../raw/indicators/Tab30.1.xml
mono cbrexporter.exe indicators Table25.1 > ../raw/indicators/Table25.1.xml
mono cbrexporter.exe indicators Table3.13 > ../raw/indicators/Table3.13.xml
mono cbrexporter.exe indicators Table3.6 > ../raw/indicators/Table3.6.xml
mono cbrexporter.exe indicators Table4.29 > ../raw/indicators/Table4.29.xml
mono cbrexporter.exe indicators Table4.6 > ../raw/indicators/Table4.6.xml
mono cbrexporter.exe indicators Table3.11 > ../raw/indicators/Table3.11.xml
mono cbrexporter.exe indicators Table3.4 > ../raw/indicators/Table3.4.xml
mono cbrexporter.exe indicators Tab29.2 > ../raw/indicators/Tab29.2.xml
mono cbrexporter.exe indicators Table24.2 > ../raw/indicators/Table24.2.xml
mono cbrexporter.exe indicators Tab29.1 > ../raw/indicators/Tab29.1.xml
mono cbrexporter.exe indicators Table24.1 > ../raw/indicators/Table24.1.xml
mono cbrexporter.exe indicators Tab28.2 > ../raw/indicators/Tab28.2.xml
mono cbrexporter.exe indicators Table23.2 > ../raw/indicators/Table23.2.xml
mono cbrexporter.exe indicators Tab28.1 > ../raw/indicators/Tab28.1.xml
mono cbrexporter.exe indicators Table23.1 > ../raw/indicators/Table23.1.xml
mono cbrexporter.exe indicators Graf2 > ../raw/indicators/Graf2.xml
mono cbrexporter.exe indicators Graf1 > ../raw/indicators/Graf1.xml
mono cbrexporter.exe indicators Graf3 > ../raw/indicators/Graf3.xml
mono cbrexporter.exe indicators Table4.46 > ../raw/indicators/Table4.46.xml
mono cbrexporter.exe indicators Table9 > ../raw/indicators/Table9.xml
mono cbrexporter.exe indicators Tab1 > ../raw/indicators/Tab1.xml
mono cbrexporter.exe indicators Table1.3 > ../raw/indicators/Table1.3.xml
mono cbrexporter.exe indicators Table1.15 > ../raw/indicators/Table1.15.xml
mono cbrexporter.exe indicators Table1.13 > ../raw/indicators/Table1.13.xml
mono cbrexporter.exe indicators Table28.2 > ../raw/indicators/Table28.2.xml
mono cbrexporter.exe indicators Table28.1 > ../raw/indicators/Table28.1.xml
mono cbrexporter.exe indicators Tab33.2 > ../raw/indicators/Tab33.2.xml
mono cbrexporter.exe indicators Tab33.1 > ../raw/indicators/Tab33.1.xml
mono cbrexporter.exe indicators Table1 > ../raw/indicators/Table1.xml
mono cbrexporter.exe indicators Table3.20 > ../raw/indicators/Table3.20.xml
mono cbrexporter.exe indicators Table3.17 > ../raw/indicators/Table3.17.xml
mono cbrexporter.exe indicators Table3.7 > ../raw/indicators/Table3.7.xml
mono cbrexporter.exe indicators Table3.8 > ../raw/indicators/Table3.8.xml
mono cbrexporter.exe indicators Table3.12 > ../raw/indicators/Table3.12.xml
mono cbrexporter.exe indicators Table3.5 > ../raw/indicators/Table3.5.xml
mono cbrexporter.exe indicators Table3.1 > ../raw/indicators/Table3.1.xml
mono cbrexporter.exe indicators Table4.31 > ../raw/indicators/Table4.31.xml
mono cbrexporter.exe indicators Table4.10 > ../raw/indicators/Table4.10.xml
mono cbrexporter.exe indicators Table4.20 > ../raw/indicators/Table4.20.xml
mono cbrexporter.exe indicators Table4.2 > ../raw/indicators/Table4.2.xml
mono cbrexporter.exe indicators Table4.30 > ../raw/indicators/Table4.30.xml
mono cbrexporter.exe indicators Table4.9 > ../raw/indicators/Table4.9.xml
mono cbrexporter.exe indicators Table4.19 > ../raw/indicators/Table4.19.xml
mono cbrexporter.exe indicators Table4.1 > ../raw/indicators/Table4.1.xml
mono cbrexporter.exe indicators Table4.11 > ../raw/indicators/Table4.11.xml
mono cbrexporter.exe indicators Table4.14 > ../raw/indicators/Table4.14.xml
mono cbrexporter.exe indicators Table4.21 > ../raw/indicators/Table4.21.xml
mono cbrexporter.exe indicators Table4.13 > ../raw/indicators/Table4.13.xml
mono cbrexporter.exe indicators Table4.33 > ../raw/indicators/Table4.33.xml
mono cbrexporter.exe indicators Table4.18 > ../raw/indicators/Table4.18.xml
mono cbrexporter.exe indicators Table4.25 > ../raw/indicators/Table4.25.xml
mono cbrexporter.exe indicators Table4.4 > ../raw/indicators/Table4.4.xml
mono cbrexporter.exe indicators Table4.12 > ../raw/indicators/Table4.12.xml
mono cbrexporter.exe indicators Table4.32 > ../raw/indicators/Table4.32.xml
mono cbrexporter.exe indicators Table4.17 > ../raw/indicators/Table4.17.xml
mono cbrexporter.exe indicators Table4.24 > ../raw/indicators/Table4.24.xml
mono cbrexporter.exe indicators Table4.3 > ../raw/indicators/Table4.3.xml
mono cbrexporter.exe indicators Table4.16 > ../raw/indicators/Table4.16.xml
mono cbrexporter.exe indicators Table4.23 > ../raw/indicators/Table4.23.xml
mono cbrexporter.exe indicators Table4.15 > ../raw/indicators/Table4.15.xml
mono cbrexporter.exe indicators Table4.22 > ../raw/indicators/Table4.22.xml
mono cbrexporter.exe indicators Table4.48 > ../raw/indicators/Table4.48.xml
mono cbrexporter.exe indicators Table4.47 > ../raw/indicators/Table4.47.xml
mono cbrexporter.exe indicators Table8 > ../raw/indicators/Table8.xml
mono cbrexporter.exe indicators Tab27.2 > ../raw/indicators/Tab27.2.xml
mono cbrexporter.exe indicators Table22.2 > ../raw/indicators/Table22.2.xml
mono cbrexporter.exe indicators Table4.8 > ../raw/indicators/Table4.8.xml
mono cbrexporter.exe indicators Table4.27 > ../raw/indicators/Table4.27.xml
mono cbrexporter.exe indicators Table4.7 > ../raw/indicators/Table4.7.xml
mono cbrexporter.exe indicators Table4.26 > ../raw/indicators/Table4.26.xml
mono cbrexporter.exe indicators Table4.37 > ../raw/indicators/Table4.37.xml
mono cbrexporter.exe indicators Table4.36 > ../raw/indicators/Table4.36.xml
mono cbrexporter.exe indicators Table4.49 > ../raw/indicators/Table4.49.xml
mono cbrexporter.exe indicators Table4.35 > ../raw/indicators/Table4.35.xml
mono cbrexporter.exe indicators Table4.34 > ../raw/indicators/Table4.34.xml
mono cbrexporter.exe indicators Table7 > ../raw/indicators/Table7.xml
mono cbrexporter.exe indicators Table10 > ../raw/indicators/Table10.xml
mono cbrexporter.exe indicators Tab32.2 > ../raw/indicators/Tab32.2.xml
mono cbrexporter.exe indicators Table27.2 > ../raw/indicators/Table27.2.xml
mono cbrexporter.exe indicators Tab32.1 > ../raw/indicators/Tab32.1.xml
mono cbrexporter.exe indicators Table27.1 > ../raw/indicators/Table27.1.xml
mono cbrexporter.exe indicators Tab31.2 > ../raw/indicators/Tab31.2.xml
mono cbrexporter.exe indicators Table26.2 > ../raw/indicators/Table26.2.xml
mono cbrexporter.exe indicators Tab31.1 > ../raw/indicators/Tab31.1.xml
mono cbrexporter.exe indicators Table26.1 > ../raw/indicators/Table26.1.xml
mono cbrexporter.exe indicators Table3.10 > ../raw/indicators/Table3.10.xml
mono cbrexporter.exe indicators Table3.9 > ../raw/indicators/Table3.9.xml
mono cbrexporter.exe indicators Table3.3 > ../raw/indicators/Table3.3.xml
mono cbrexporter.exe indicators Table3.2 > ../raw/indicators/Table3.2.xml
mono cbrexporter.exe indicators Table4.28 > ../raw/indicators/Table4.28.xml
mono cbrexporter.exe indicators Table4.5 > ../raw/indicators/Table4.5.xml
mono cbrexporter.exe indicators Table1.12 > ../raw/indicators/Table1.12.xml
mono cbrexporter.exe indicators Table1.8 > ../raw/indicators/Table1.8.xml
mono cbrexporter.exe indicators Table1.7 > ../raw/indicators/Table1.7.xml
mono cbrexporter.exe indicators Tab27.1 > ../raw/indicators/Tab27.1.xml
mono cbrexporter.exe indicators Table22.1 > ../raw/indicators/Table22.1.xml
mono cbrexporter.exe indicators Table11 > ../raw/indicators/Table11.xml
